### ISSUE TITLE
failed on RTL Websites

### ISSUE THREAD

**Issue by ali-hellani** [coreysyms/FoundationGridBalancer#1]
it is not working when the website is using RTL (right to left languages). despite that foundation supports RTL [http://foundation.zurb.com/docs/components/rtl.html]

**for instance:** `margin-left` must be `margin-right`

**Comment by coreysyms** [comment]
Thanks Ali. Will take a look and make this fix today. Will be a simple fix. Thanks for reporting

Corey Snyder

**Comment by ali-hellani** [comment]
thanks for your hard work, your plugin saved my day. :relieved:

i have already changed all `margin-left` to `margin-right`, because in my case it is not necessary to check if the website is **RTL** or not.

beside that i have added also the following before "small only" check:

``` javascript
//xsmall only
if (matchMedia(Foundation.media_queries['xsmall']).matches && gridMediaSize == "xsmall") {
    grid = 1;
    break;
}
```

it is for screens below 360px, and it works like a charm :+1:
**Note:** xsmall is a custom defined media

**Comment by coreysyms** [comment]
Thanks again for the heads up Ali. Added in RTL support now, issue closed.
