### ISSUE TITLE
Toggle Respect Rule

### ISSUE THREAD

**Issue by Ne-Ne** [coreysyms/FoundationGridBalancer#2]
Firstly great plugin!

Not an issue.. But is there someway that rather than initialising the plugin using, as follows:

``` html
data-balancer
```

But use it as follows:

``` html
data-balancer="respect"
```

or

``` html
data-balancer="no-respect"
```

If nothing is entered is falls back to default. I would love to use this on my site however I can use both settings? Unless I use script tags inline on page, compared to including it in my scripts file..

What do you think?

**Comment by Ne-Ne** [comment]
Hi @coreysyms,

To add to the above, I have done some changes, to make the code work Foundation for site (latest version). What do you think?

http://codepen.io/Ne-Ne/pen/YwVqOq (ref)

**Comment by coreysyms** [comment]
I like the data attribute suggestion, never thought about it being used differently on the same site or page. Will look to include this in the next version when I upgrade for F6. Thanks for the codepen as well.

**Comment by coreysyms** [comment]
@Ne-Ne your suggestion has been added, but as a part of the wholesale upgrade for Foundation 6, which I would hope you would be on anyhow, cause it's awesome ;). Happy coding. Corey.
